#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

selected=`cat $SCRIPT_DIR/cht-languages $SCRIPT_DIR/cht-commands | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" ./cht-languages; then
    curl -s cht.sh/$selected/$query | less
else
    curl -s cht.sh/$selected~$query | less
fi
