#!/usr/bin/env bash
selected=`cat ./cht-languages ./cht-commands | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" ./cht-languages; then
    curl -s cht.sh/$selected/$query | less
else
    curl -s cht.sh/$selected~$query | less
fi
